alert MAT disclaimer
Teradata/design-system pull request #23
Opened 2024-08-14 19:05 UTC by ObedVega

2024-08-19 14:30 UTC, owilliams320 requested changes
Just a few small comments, but overall 👍🏽

2024-08-19 14:30 UTC, owilliams320 commented on libs/react-components/src/lib/components/Alert/Alert.stories.tsx
> +          <IconButton icon="close" />
can we do without the div? it works but its simpler to just add the slot name to the single item here.

```suggestion
          <IconButton slot="action-items" icon="close" />
```

2024-08-19 14:30 UTC, owilliams320 commented on libs/react-components/src/lib/components/Alert/styles.module.scss
> +.alertWrapper {
was this style needed?

2024-08-19 15:28 UTC, ObedVega commented on libs/react-components/src/lib/components/Alert/styles.module.scss
> +.alertWrapper {
not need anymore

2024-08-19 16:12 UTC, bsahitya submitted a review, later dismissed
LGTM! 🚀

2024-08-19 23:03 UTC, owilliams320 approved these changes

2024-08-19 23:03 UTC, merged

2024-08-22 15:40 UTC, owilliams320 commented
:tada: This issue has been resolved in version 1.10.1 :tada:

The release is available on:
- `v1.10.1`
- [GitHub release](https://github.com/Teradata/design-system/releases/tag/v1.10.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: